name: Run address matcher with external labels

on:
  workflow_dispatch:

jobs:
  run-address-matcher:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Clone address_matching_labels repo
      env:
        LABELS_PAT: ${{ secrets.LABELS_PAT }}
      run: |
        git clone https://RobinL:${LABELS_PAT}@github.com/RobinL/address_matching_labels.git

    - name: Run match_addresses.py
      run: uv run address_matching_labels/match_addresses.py